name: Main CI


on: [push]


jobs:
  run_tests:
    runs-on: ubuntu-latest

    environment: tests

    env:
      HOME_URL: ${{vars.HOME_URL}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

        with:
          python-version: 3.11.4

      - name: Install dependences
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install project
        run: |
          poetry install

      - name: Run Tests
        run: |
          poetry run pytest

      - name: Run mypy
        run: |
          poetry run mypy ./

      - name: Run pylint
        run: |
          poetry run pylint ./app_fastapi
  
  build:
    runs-on: ubuntu-latest

    needs: [run_tests]

    steps:
      - name: Login to Docker
        run: echo ${{secrets.DOCKER_TOKEN}} | docker login -u ${{ secrets.DOCKER_LOGIN}} --password-stdin

      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build --pull --rm -f "./DockerFile" -t ${{ vars.DOCKER_PROJECT}}:${GITHUB_REF_NAME} "app-fastapi" --tag fastapi

      - name: Push image to dockerhub
        run: docker push ${{ vars.DOCKER_PROJECT}}:${GITHUB_REF_NAME}